import { useCallback, useEffect, useMemo, useState } from "react";
import { NavLink, useLocation } from "react-router-dom";
import { toast } from "sonner";
import { PageHeader } from "@/components/layout/PageHeader";
import { Button } from "@/components/ui/Button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/Card";
import { Input } from "@/components/ui/Input";
import { useAuth } from "@/hooks/useAuth";
import { communicationService } from "@/services/communicationService";

type Data = Awaited<ReturnType<typeof communicationService.load>>;
const tabs=["gateways","project-groups","rules","templates","deliveries","logs","test"] as const;
const labels:{[K in typeof tabs[number]]:string}={gateways:"Gateways","project-groups":"Project Groups",rules:"Rules",templates:"Templates",deliveries:"Deliveries",logs:"Logs",test:"Test Center"};
const tableClass="w-full min-w-[720px] text-left text-sm";

export function CommunicationCenterPage(){
  const{user}=useAuth(); const location=useLocation(); const active=location.pathname.split("/")[2]||"dashboard";
  const[data,setData]=useState<Data>(); const[loading,setLoading]=useState(true); const[projectId,setProjectId]=useState(""); const[groupKey,setGroupKey]=useState(""); const[testMessage,setTestMessage]=useState("TEST — Site Connect Communication Center connectivity check.");
  const load=useCallback(async()=>{if(!user)return;setLoading(true);try{setData(await communicationService.load(user));}catch(error){toast.error(error instanceof Error?error.message:"Unable to load Communication Center.");}finally{setLoading(false);}},[user]);
  useEffect(()=>{void load();},[load]);
  const summary=useMemo(()=>{const deliveries=data?.deliveries??[];return {pending:deliveries.filter(x=>x.status==="pending").length,approval:deliveries.filter(x=>x.status==="awaiting_approval").length,processing:deliveries.filter(x=>x.status==="processing").length,sent:deliveries.filter(x=>x.status==="sent").length,failed:deliveries.filter(x=>x.status==="failed").length,suppressed:deliveries.filter(x=>x.status==="suppressed").length};},[data]);
  if(!user)return null;
  async function mutate(action:()=>Promise<void>,message:string){try{await action();toast.success(message);await load();}catch(error){toast.error(error instanceof Error?error.message:"Action failed.");}}
  const selectedGroup=data?.groups.find(group=>`${group.gatewayId}|${group.id}`===groupKey);
  return <>
    <PageHeader title="Communication Center" description="Independent, approval-first DPR notification operations. Attendance notifications are disabled." breadcrumbs={[{label:"Home",to:"/home"},{label:"Communication Center"}]}/>
    <div className="mb-5 flex flex-wrap gap-2"><NavLink className="rounded-md border px-3 py-2 text-sm font-semibold" to="/communication-center">Dashboard</NavLink>{tabs.map(tab=><NavLink key={tab} className="rounded-md border px-3 py-2 text-sm font-semibold" to={`/communication-center/${tab}`}>{labels[tab]}</NavLink>)}</div>
    {active==="dashboard"?<div className="grid gap-4 md:grid-cols-3 xl:grid-cols-6">{Object.entries(summary).map(([key,value])=><Card key={key}><CardContent className="p-4"><p className="text-xs uppercase text-text-secondary">{key}</p><p className="mt-2 text-2xl font-bold">{value}</p></CardContent></Card>)}<Card className="md:col-span-3 xl:col-span-6"><CardHeader><CardTitle>Gateway health</CardTitle></CardHeader><CardContent>{data?.gateways.map(g=><p key={g.id} className="mb-2 text-sm"><b>{g.displayName}</b> — {g.status} · linked {g.linkedNumber??"not paired"} · heartbeat {g.lastSeenAt??"never"}{g.paused?" · PAUSED":""}</p>)}{!data?.gateways.length?<p className="text-sm text-text-secondary">No gateway configured.</p>:null}</CardContent></Card></div>:null}
    {active==="gateways"?<Table headers={["Gateway","Provider status","Linked number","Last heartbeat","Circuit"]} rows={(data?.gateways??[]).map(g=>[g.displayName,g.status,g.linkedNumber??"—",g.lastSeenAt??"—",g.paused?"Paused":"Ready"])} />:null}
    {active==="project-groups"?<div className="space-y-4"><Card><CardHeader><CardTitle>Map an approved project group</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-3"><select className="h-11 rounded-md border px-3" value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Select project</option>{data?.projects.map(p=><option value={p.id} key={p.id}>{p.code} — {p.name}</option>)}</select><select className="h-11 rounded-md border px-3" value={groupKey} onChange={e=>setGroupKey(e.target.value)}><option value="">Select synced WhatsApp group</option>{data?.groups.map(g=><option value={`${g.gatewayId}|${g.id}`} key={`${g.gatewayId}|${g.id}`}>{g.name} ({g.participantCount})</option>)}</select><Button disabled={!projectId||!selectedGroup} onClick={()=>selectedGroup&&void mutate(()=>communicationService.mapProject(user,{projectId,gatewayId:selectedGroup.gatewayId,groupId:selectedGroup.id,groupName:selectedGroup.name}),"Project group mapped.")}>Save mapping</Button></CardContent></Card><Table headers={["Project","Gateway","Approved group","Participants","DPR","Active","Last sync","Action"]} rows={(data?.mappings??[]).map(m=>[`${m.projectCode} — ${m.projectName}`,m.gatewayId,m.destinationGroupName,String(m.participantCount),m.dprEnabled?"Enabled":"Disabled",m.active?"Active":"Inactive",m.lastSyncedAt??"—",<Button key={m.id} size="sm" variant="secondary" onClick={()=>void mutate(()=>communicationService.setMapping(user,m.id,{active:!m.active}),"Mapping updated.")}>{m.active?"Disable":"Enable"}</Button>])}/></div>:null}
    {active==="rules"?<Table headers={["Event","Enabled","Approval","Mode","Attempts","Priority","Action"]} rows={(data?.rules??[]).map(r=>[r.eventType,r.enabled?"Yes":"No",r.approvalRequired?"Required":"Automatic",r.deliveryMode,String(r.maxAttempts),String(r.priority),<Button key={r.id} size="sm" variant="secondary" onClick={()=>void mutate(()=>communicationService.setRule(user,r.id,{enabled:!r.enabled}),"Rule updated.")}>{r.enabled?"Disable":"Enable"}</Button>])}/>:null}
    {active==="templates"?<Table headers={["Template","Event","Caption template","State"]} rows={(data?.templates??[]).map(t=>[t.templateName,t.eventType,t.content,t.isActive?"Active":"Inactive"])}/>:null}
    {active==="deliveries"?<Table headers={["Time","Event","Destination","Type","Status","Attempts","Provider ID / Error","Actions"]} rows={(data?.deliveries??[]).map(d=>[d.createdAt,d.eventType,d.destination??"—",d.messageType,d.status,String(d.attemptCount),d.providerMessageId??d.lastError??"—",<span key={d.id} className="flex gap-1">{d.status==="awaiting_approval"?<Button size="sm" onClick={()=>void mutate(()=>communicationService.deliveryAction(user,d.id,"approve"),"Delivery approved.")}>Approve</Button>:null}{d.status==="failed"?<Button size="sm" onClick={()=>void mutate(()=>communicationService.deliveryAction(user,d.id,"retry"),"Delivery queued for retry.")}>Retry</Button>:null}{["pending","awaiting_approval","failed"].includes(d.status)?<Button size="sm" variant="secondary" onClick={()=>window.confirm("Cancel this delivery?")&&void mutate(()=>communicationService.deliveryAction(user,d.id,"cancel"),"Delivery cancelled.")}>Cancel</Button>:null}</span>])}/>:null}
    {active==="logs"?<Table headers={["Time","Severity","Event","Message"]} rows={(data?.logs??[]).map(log=>[log.createdAt,log.level,log.eventType,log.message])}/>:null}
    {active==="test"?<Card><CardHeader><CardTitle>Approval-first test message</CardTitle></CardHeader><CardContent className="space-y-3"><select className="h-11 w-full rounded-md border px-3" value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Select mapped project</option>{data?.mappings.filter(m=>m.active).map(m=><option key={m.projectId} value={m.projectId}>{m.projectCode} — {m.projectName} → {m.destinationGroupName}</option>)}</select><Input value={testMessage} onChange={e=>setTestMessage(e.target.value)}/><p className="text-xs text-text-secondary">The message is visibly labelled TEST and can only target the selected approved group.</p><Button disabled={!projectId||!testMessage.trim()} onClick={()=>window.confirm("Queue this TEST message for admin approval?")&&void mutate(()=>communicationService.queueTest(user,projectId,testMessage),"Test queued for approval.")}>Queue test</Button></CardContent></Card>:null}
    {loading?<p className="mt-4 text-sm text-text-secondary">Loading Communication Center…</p>:null}
  </>;
}

function Table({headers,rows}:{headers:string[];rows:(React.ReactNode[])[]}){return <Card><CardContent className="overflow-x-auto p-0"><table className={tableClass}><thead><tr>{headers.map(h=><th className="border-b bg-slate-50 px-4 py-3" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td className="border-b px-4 py-3 align-top" key={j}>{cell}</td>)}</tr>)}</tbody></table>{!rows.length?<p className="p-5 text-sm text-text-secondary">No records found.</p>:null}</CardContent></Card>}
