/* eslint-disable @typescript-eslint/no-explicit-any -- Supabase runtime rows are mapped at this boundary. */
import { isSupabaseConfigured, supabase } from "@/services/supabaseClient";
import { storageService } from "@/services/storageService";
import type { AppUser } from "@/types/auth";
import type { DetailedClaimVoucher } from "@/types/claims";
import type { SapExportBatch,SapExportRow,SapMapping } from "@/types/sap";

const HEADERS=["Document Date","Posting Date","Company Code","Currency","Employee/Vendor Code","GL Code","Cost Center","Profit Center","Project Code","Customer Code","Expense Category","Narration","Debit Amount","Credit Amount","Claim Number","Voucher Number"];
const escape=(v:unknown)=>`"${String(v??"").replace(/"/g,'""')}"`;
export function sapRowsToCsv(rows:SapExportRow[],companyCode="IPI",currency="INR"){return [HEADERS.join(","),...rows.map(r=>[r.documentDate,r.postingDate,companyCode,currency,r.employeeVendorCode,r.glCode,r.costCenter,r.profitCenter,r.projectId,r.customerId,r.expenseCategoryId,r.narration,r.debitCredit==="debit"?r.amount:0,r.debitCredit==="credit"?r.amount:0,r.claimNumber??r.claimId,r.voucherNumber??r.voucherId].map(escape).join(","))].join("\r\n");}
export function downloadSapCsv(batch:SapExportBatch){const url=URL.createObjectURL(new Blob([sapRowsToCsv(batch.items??[])],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=batch.fileName??`${batch.batchNumber}.csv`;a.click();URL.revokeObjectURL(url);}
function requireClient(){if(!isSupabaseConfigured||!supabase)throw new Error("Supabase is required for SAP exports.");return supabase;}
const mapItem=(r:any):SapExportRow=>({id:r.id,batchId:r.sap_batch_id,voucherId:r.voucher_id,claimId:r.claim_id,employeeId:r.employee_id,projectId:r.project_id??undefined,customerId:r.customer_id??undefined,costCodeId:r.cost_code_id??undefined,expenseCategoryId:r.expense_category_id??undefined,glCode:r.sap_gl_code,costCenter:r.sap_cost_center??"",profitCenter:r.sap_profit_center??undefined,employeeVendorCode:r.sap_vendor_or_employee_code,postingDate:r.posting_date,documentDate:r.document_date,amount:Number(r.amount),debitCredit:r.debit_credit,narration:r.narration??""});
export const sapExportService={
 async listPending(user:AppUser):Promise<DetailedClaimVoucher[]>{if(!["accounts_officer","super_admin"].includes(user.role))return[];const c=requireClient();const{data,error}=await c.from("claim_payment_vouchers").select("*").in("id",(await c.from("claim_payment_voucher_items").select("voucher_id,claims!inner(status)").eq("claims.status","sap_export_pending")).data?.map((r:any)=>r.voucher_id)??[]);if(error)throw new Error(error.message);return(data??[]).map((v:any)=>({id:v.id,claimId:"",claimIds:[],voucherNumber:v.voucher_number,voucherType:v.voucher_type,voucherDate:v.voucher_date,employeeId:v.employee_id,paidToName:v.employee_name_snapshot,paidToEmail:v.employee_email_snapshot??"",approvedAmount:Number(v.net_payable_amount),grossClaimedAmount:Number(v.gross_claimed_amount),grossVerifiedAmount:Number(v.gross_verified_amount),deductionAmount:Number(v.gross_deduction_amount),netPayableAmount:Number(v.net_payable_amount),preparedBy:v.prepared_by??user.id,preparedByName:user.fullName,status:"generated",createdAt:v.created_at,items:[],attachments:[]}));},
 async generate(voucherIds:string[],type:"preview"|"final",remarks="",user?:AppUser|null){const c=requireClient();const{data,error}=await c.rpc("generate_claim_sap_batch",{p_voucher_ids:voucherIds,p_export_type:type,p_remarks:remarks||null});if(error)throw new Error(error.message);const batch=await this.getBatch(String(data));if(user){const csv=sapRowsToCsv(batch.items??[]);const [stored]=await storageService.uploadFiles("sap-exports",[new File([csv],batch.fileName??`${batch.batchNumber}.csv`,{type:"text/csv;charset=utf-8"})],user,batch.id);const{error:updateError}=await c.from("claim_sap_export_batches").update({file_path:stored.path,file_name:stored.fileName}).eq("id",batch.id);if(updateError)throw new Error(updateError.message);batch.filePath=stored.path;}return batch;},
 async listBatches():Promise<SapExportBatch[]>{const{data,error}=await requireClient().from("claim_sap_export_batches").select("*").order("export_date",{ascending:false});if(error)throw new Error(error.message);return(data??[]).map((b:any)=>({id:b.id,batchNumber:b.sap_batch_number,exportDate:b.export_date,exportedBy:b.exported_by,exportType:b.export_type,fileName:b.file_name??undefined,filePath:b.file_path??undefined,totalClaims:b.total_claims,totalVouchers:b.total_vouchers,totalAmount:Number(b.total_amount),status:b.status,remarks:b.remarks??undefined}));},
 async getBatch(id:string):Promise<SapExportBatch>{const c=requireClient();const[b,i]=await Promise.all([c.from("claim_sap_export_batches").select("*").eq("id",id).single(),c.from("claim_sap_export_items").select("*").eq("sap_batch_id",id)]);if(b.error)throw new Error(b.error.message);if(i.error)throw new Error(i.error.message);const x=b.data as any;return{id:x.id,batchNumber:x.sap_batch_number,exportDate:x.export_date,exportedBy:x.exported_by,exportType:x.export_type,fileName:x.file_name??undefined,filePath:x.file_path??undefined,totalClaims:x.total_claims,totalVouchers:x.total_vouchers,totalAmount:Number(x.total_amount),status:x.status,remarks:x.remarks??undefined,items:(i.data??[]).map(mapItem)};},
 async downloadStored(batch:SapExportBatch){if(!batch.filePath){downloadSapCsv(batch);return;}const url=await storageService.createSignedUrl("sap-exports",batch.filePath);const a=document.createElement("a");a.href=url;a.download=batch.fileName??`${batch.batchNumber}.csv`;a.click();},
 async listMappingOptions(){const c=requireClient();const[e,p,cu,d]=await Promise.all([c.from("expense_categories").select("id,name").eq("status","active").order("name"),c.from("project_cost_codes").select("id,code,name").eq("status","active").order("code"),c.from("customers").select("id,customer_code,customer_name").eq("status","active").order("customer_name"),c.from("departments").select("id,department_code,department_name").eq("status","active").order("department_name")]);for(const result of[e,p,cu,d])if(result.error)throw new Error(result.error.message);return{expenseCategories:(e.data??[]).map((x:any)=>({id:x.id,label:`${x.name} (${x.id})`})),costCodes:(p.data??[]).map((x:any)=>({id:x.id,label:`${x.code} - ${x.name}`})),customers:(cu.data??[]).map((x:any)=>({id:x.id,label:`${x.customer_code} - ${x.customer_name}`})),departments:(d.data??[]).map((x:any)=>({id:x.id,label:`${x.department_code} - ${x.department_name}`}))};},
 async cancel(id:string){const{error}=await requireClient().rpc("cancel_claim_sap_batch",{p_batch_id:id});if(error)throw new Error(error.message);},
 async listMappings():Promise<SapMapping[]>{const{data,error}=await requireClient().from("sap_gl_mappings").select("*").order("created_at");if(error)throw new Error(error.message);return(data??[]).map((m:any)=>({id:m.id,expenseCategoryId:m.expense_category_id??undefined,projectCostCodeId:m.project_cost_code_id??undefined,customerId:m.customer_id??undefined,departmentId:m.department_id??undefined,glCode:m.sap_gl_code,costCenter:m.sap_cost_center??undefined,profitCenter:m.sap_profit_center??undefined,companyCode:m.company_code,postingGroup:m.posting_group??"other",active:m.active}));},
 async saveMapping(m:Omit<SapMapping,"id">&{id?:string},user:AppUser){const payload={organization_id:user.organizationId,expense_category_id:m.expenseCategoryId||null,project_cost_code_id:m.projectCostCodeId||null,customer_id:m.customerId||null,department_id:m.departmentId||null,sap_gl_code:m.glCode,sap_cost_center:m.costCenter||null,sap_profit_center:m.profitCenter||null,company_code:m.companyCode,posting_group:m.postingGroup??"other",active:m.active};const q=m.id?requireClient().from("sap_gl_mappings").update(payload).eq("id",m.id):requireClient().from("sap_gl_mappings").insert(payload);const{error}=await q;if(error)throw new Error(error.message);}
};
