import JSZip from "jszip";
import type { SapExportRow } from "@/types/sap";

const HEADERS=["Document Date","Posting Date","Company Code","Currency","Employee/Vendor Code","GL Code","Cost Center","Profit Center","Project Code","Customer Code","Expense Category","Narration","Debit Amount","Credit Amount","Claim Number","Voucher Number"];
const xml=(value:unknown)=>String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
function col(index:number){let result="";for(let n=index+1;n;n=Math.floor((n-1)/26))result=String.fromCharCode(65+(n-1)%26)+result;return result}
const dateSerial=(value:string)=>Math.floor((Date.parse(`${value}T00:00:00Z`)-Date.UTC(1899,11,30))/86400000);
const rowValues=(r:SapExportRow)=>[r.documentDate,r.postingDate,"IPI","INR",r.employeeVendorCode,r.glCode,r.costCenter,r.profitCenter??"",r.projectId??"",r.customerId??"",r.expenseCategoryId??"",r.narration,r.debitCredit==="debit"?r.amount:0,r.debitCredit==="credit"?r.amount:0,r.claimNumber??r.claimId,r.voucherNumber??r.voucherId];
function sheet(rows:SapExportRow[]){const values=[HEADERS,...rows.map(rowValues)];const data=values.map((row,ri)=>`<row r="${ri+1}">${row.map((value,ci)=>{const ref=`${col(ci)}${ri+1}`;if(ri===0)return `<c r="${ref}" t="inlineStr" s="1"><is><t>${xml(value)}</t></is></c>`;if(ci<2)return `<c r="${ref}" s="2"><v>${dateSerial(String(value))}</v></c>`;if(ci===12||ci===13)return `<c r="${ref}" s="3"><v>${Number(value)}</v></c>`;return `<c r="${ref}" t="inlineStr"><is><t>${xml(value)}</t></is></c>`}).join("")}</row>`).join("");return `<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" state="frozen"/></sheetView></sheetViews><sheetData>${data}</sheetData><autoFilter ref="A1:P${values.length}"/></worksheet>`}

export async function createSapWorkbook(rows:SapExportRow[]){const zip=new JSZip();zip.file("[Content_Types].xml",`<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>`);zip.file("_rels/.rels",`<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`);zip.file("xl/workbook.xml",`<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Preview" sheetId="1" r:id="rId1"/><sheet name="Final Export" sheetId="2" r:id="rId2"/></sheets></workbook>`);zip.file("xl/_rels/workbook.xml.rels",`<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`);zip.file("xl/styles.xml",`<?xml version="1.0"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font/><font><b/><color rgb="FFFFFFFF"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF005EB8"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="4"><xf/><xf fontId="1" fillId="2" applyFont="1" applyFill="1"/><xf numFmtId="14" applyNumberFormat="1"/><xf numFmtId="44" applyNumberFormat="1"/></cellXfs></styleSheet>`);zip.file("xl/worksheets/sheet1.xml",sheet(rows));zip.file("xl/worksheets/sheet2.xml",sheet(rows));return zip.generateAsync({type:"uint8array",compression:"DEFLATE"})}
