import {
  BarChart3,
  Building2,
  CalendarCheck2,
  CalendarDays,
  ClipboardCheck,
  Clock3,
  Droplets,
  Fuel,
  HardHat,
  Home,
  MessageSquareText,
  MapPinned,
  ReceiptText,
  WalletCards,
  Settings,
  Truck,
  Users,
} from "lucide-react";

import type { Role } from "@/types/auth";
import type {
  ModuleDefinition,
  ModuleKey,
  ModuleLandingContent,
} from "@/types/modules";

const allRoles: Role[] = [
  "site_staff",
  "manager",
  "hod",
  "admin_hr",
  "super_admin",
  "accounts_officer",
];

const officeRoles: Role[] = [
  "manager",
  "hod",
  "admin_hr",
  "super_admin",
  "accounts_officer",
];

export const MODULES: ModuleDefinition[] = [
  {
    key: "dashboard",
    name: "Dashboard",
    path: "/dashboard",
    description: "Role-based operational summary and quick actions.",
    icon: BarChart3,
    allowedRoles: allRoles,
    accent: "blue",
    category: "core",
  },
  {
    key: "claims",
    name: "Claims",
    path: "/claims",
    description: "Submit, verify, approve, voucher and pay expenses.",
    icon: ReceiptText,
    allowedRoles: allRoles,
    pendingCountKey: "claims",
    accent: "orange",
    category: "finance",
  },
  {
    key: "attendance",
    name: "Attendance",
    path: "/attendance",
    description: "GPS check-in, register, admin edits and monthly summaries.",
    icon: Clock3,
    allowedRoles: ["site_staff", "manager", "hod", "admin_hr", "super_admin"],
    pendingCountKey: "attendance",
    accent: "green",
    category: "people",
  },
  {
    key: "leave",
    name: "Leave",
    path: "/leave",
    description: "Apply leave, approve requests and manage balances.",
    icon: CalendarDays,
    allowedRoles: ["site_staff", "manager", "hod", "admin_hr", "super_admin"],
    pendingCountKey: "leave",
    accent: "blue",
    category: "people",
  },
  {
    key: "tasks",
    name: "Tasks",
    path: "/tasks",
    description: "Create, assign, comment and track task progress.",
    icon: ClipboardCheck,
    allowedRoles: ["site_staff", "manager", "hod", "admin_hr", "super_admin"],
    pendingCountKey: "tasks",
    accent: "slate",
    category: "core",
  },
  {
    key: "messages",
    name: "Messages",
    path: "/messages",
    description: "Team conversations, file sharing and read receipts.",
    icon: MessageSquareText,
    allowedRoles: allRoles,
    pendingCountKey: "messages",
    accent: "blue",
    category: "communication",
  },
  {
    key: "field_operations",
    name: "DPR / Field Ops",
    path: "/field-operations",
    description: "Daily progress, site photos, issues and next-day plans.",
    icon: HardHat,
    allowedRoles: ["site_staff", "manager", "hod", "admin_hr", "super_admin"],
    pendingCountKey: "fieldOperations",
    accent: "orange",
    category: "operations",
  },
  {
    key: "casual_labour",
    name: "Casual Labour",
    path: "/casual-labour",
    description: "Temporary labour attendance, registers and cost tracking.",
    icon: Users,
    allowedRoles: ["site_staff", "manager", "hod", "admin_hr", "super_admin"],
    accent: "green",
    category: "operations",
  },
  {
    key: "machinery",
    name: "Machinery",
    path: "/machinery",
    description: "Contracts, logs, usage, breakdowns and reports.",
    icon: Truck,
    allowedRoles: ["site_staff", "manager", "hod", "admin_hr", "super_admin"],
    accent: "slate",
    category: "operations",
  },
  {
    key: "fuel",
    name: "Fuel",
    path: "/fuel",
    description: "Receipts, issues, machine consumption and stock.",
    icon: Fuel,
    allowedRoles: ["site_staff", "manager", "hod", "admin_hr", "super_admin"],
    accent: "orange",
    category: "operations",
  },
  {
    key: "materials",
    name: "Materials",
    path: "/materials",
    description: "Requests, receipts, consumption and inventory reports.",
    icon: Droplets,
    allowedRoles: ["site_staff", "manager", "hod", "admin_hr", "super_admin"],
    accent: "blue",
    category: "operations",
  },
  {
    key: "vendors",
    name: "Vendors",
    path: "/vendors",
    description: "Vendor master, contracts, bills, vouchers and ledger.",
    icon: Building2,
    allowedRoles: officeRoles,
    pendingCountKey: "vendors",
    accent: "slate",
    category: "finance",
  },
  {
    key: "accounts",
    name: "Accounts",
    path: "/accounts",
    description: "Claim verification, vouchers, SAP exports, ledgers and reconciliation.",
    icon: WalletCards,
    allowedRoles: ["accounts_officer", "super_admin"],
    accent: "green",
    category: "finance",
  },
  {
    key: "reports",
    name: "Reports",
    path: "/reports",
    description: "Filters, charts and exports for every operational module.",
    icon: CalendarCheck2,
    allowedRoles: officeRoles,
    accent: "blue",
    category: "admin",
  },
  {
    key: "settings",
    name: "Settings & Master Data",
    path: "/settings",
    description: "Company, workflows, masters and notification settings.",
    icon: Settings,
    allowedRoles: ["admin_hr", "super_admin"],
    accent: "slate",
    category: "admin",
  },
  {
    key: "users",
    name: "User Management",
    path: "/users",
    description: "Invite users, assign roles and manage reporting lines.",
    icon: Home,
    allowedRoles: ["admin_hr", "super_admin"],
    accent: "blue",
    category: "admin",
  },
  {
    key: "projects",
    name: "Project / Site Master",
    path: "/projects",
    description: "Projects, sites, managers, departments, users and cost codes.",
    icon: MapPinned,
    allowedRoles: ["admin_hr", "super_admin"],
    accent: "green",
    category: "admin",
  },
];

export const MODULE_BY_KEY = MODULES.reduce(
  (modules, module) => ({
    ...modules,
    [module.key]: module,
  }),
  {} as Record<ModuleKey, ModuleDefinition>,
);

export const MODULE_BY_PATH = MODULES.reduce(
  (modules, module) => ({
    ...modules,
    [module.path]: module,
  }),
  {} as Record<string, ModuleDefinition>,
);

export function getVisibleModules(role: Role) {
  return MODULES.filter((module) => module.allowedRoles.includes(role));
}

export const MODULE_LANDING_CONTENT: Record<ModuleKey, ModuleLandingContent> = {
  dashboard: {
    title: "Dashboard",
    description: "A role-based summary of work, approvals and risks.",
    primaryActions: ["Review metrics", "Open pending approvals", "Export summary"],
    workflow: ["Collect module signals", "Highlight exceptions", "Guide action"],
  },
  claims: {
    title: "Claims & Finance",
    description: "Expense submission, verification, approvals and payment flow.",
    primaryActions: ["Submit claim", "Review queue", "Generate voucher"],
    workflow: [
      "Employee submits",
      "Admin verifies",
      "Manager approves",
      "Finance authorizes payment",
    ],
  },
  attendance: {
    title: "Attendance",
    description: "Daily check-in, check-out, registers and admin corrections.",
    primaryActions: ["Check in", "Open register", "Review exceptions"],
    workflow: ["Capture location", "Record punch", "Summarize month"],
  },
  leave: {
    title: "Leave Management",
    description: "Policy-backed leave applications, balances and approvals.",
    primaryActions: ["Apply leave", "Review requests", "Open calendar"],
    workflow: ["Check balance", "Submit dates", "Approve or reject"],
  },
  tasks: {
    title: "Task Management",
    description: "Assign work, track progress and resolve overdue tasks.",
    primaryActions: ["Create task", "Update progress", "Review overdue"],
    workflow: ["Assign", "Track", "Close"],
  },
  messages: {
    title: "Messaging",
    description: "One-to-one and group communication for project teams.",
    primaryActions: ["Open inbox", "Start chat", "Search conversations"],
    workflow: ["Send", "Read", "Archive"],
  },
  field_operations: {
    title: "Field Operations",
    description: "DPRs, photos, progress, labour, machinery, fuel and materials.",
    primaryActions: ["Submit DPR", "Review history", "Open reports"],
    workflow: ["Capture site data", "Submit report", "Analyze progress"],
  },
  casual_labour: {
    title: "Casual Labour",
    description: "Register temporary labour attendance and site allocations.",
    primaryActions: ["Mark attendance", "Open register", "Export labour cost"],
    workflow: ["Record labour", "Validate day", "Calculate cost"],
  },
  machinery: {
    title: "Machinery",
    description: "Machine contracts, daily usage logs and breakdown tracking.",
    primaryActions: ["Log usage", "Open contracts", "Review breakdowns"],
    workflow: ["Contract", "Operate", "Report"],
  },
  fuel: {
    title: "Fuel",
    description: "Fuel receipts, issues, stock and consumption analysis.",
    primaryActions: ["Record receipt", "Issue fuel", "Check stock"],
    workflow: ["Receive", "Issue", "Reconcile"],
  },
  materials: {
    title: "Materials",
    description: "Requests, receipts and project material consumption.",
    primaryActions: ["Request material", "Record receipt", "Log consumption"],
    workflow: ["Request", "Receive", "Consume"],
  },
  vendors: {
    title: "Vendor Management",
    description: "Vendor profiles, bills, payments, vouchers and ledgers.",
    primaryActions: ["Add vendor", "Review bills", "Open ledger"],
    workflow: ["Register", "Contract", "Settle"],
  },
  accounts: {
    title: "Accounts",
    description: "Approved payment processing, ledgers and reconciliation.",
    primaryActions: ["Verify claims", "Generate voucher", "Export SAP", "Reconcile"],
    workflow: ["Verify", "Voucher", "SAP", "Pay", "Reconcile"],
  },
  reports: {
    title: "Reports & Analytics",
    description: "Operational, financial and project reports with exports.",
    primaryActions: ["Filter report", "Download PDF", "Export Excel"],
    workflow: ["Filter", "Analyze", "Export"],
  },
  settings: {
    title: "Settings",
    description: "System-wide masters, workflow rules and notification controls.",
    primaryActions: ["Company settings", "Workflow settings", "Master data"],
    workflow: ["Configure", "Validate", "Audit"],
  },
  users: {
    title: "User Management",
    description: "User invitations, roles, reporting lines and account status.",
    primaryActions: ["Invite user", "Assign role", "Review access"],
    workflow: ["Invite", "Authorize", "Audit"],
  },
  projects: {
    title: "Project / Site Master",
    description: "Maintain sites, project hierarchy and project-linked master data.",
    primaryActions: ["Add project", "Assign users", "Manage cost codes"],
    workflow: ["Create site", "Link teams", "Control budgets"],
  },
};
