import {
  DEMO_DEPARTMENT_IDS,
  DEMO_DESIGNATION_IDS,
  DEMO_ORGANIZATION_ID,
} from "@/constants/demoData";
import type {
  ApprovalDelegation,
  ApprovalMatrixRule,
  Department,
  Designation,
  Organization,
} from "@/types/organization";

const createdAt = "2026-06-21T00:00:00.000Z";

export const DEMO_ORGANIZATION: Organization = {
  id: DEMO_ORGANIZATION_ID,
  organizationCode: "IPI",
  organizationName: "IPI Site Connect",
  legalName: "IPI Site Connect Private Limited",
  gstNumber: "29AABCI1234F1Z5",
  panNumber: "AABCI1234F",
  address: "Site Connect House, MG Road",
  city: "Bengaluru",
  state: "Karnataka",
  country: "India",
  pincode: "560001",
  supportEmail: "support@siteconnect.local",
  supportPhone: "+91 98765 00000",
  currency: "INR",
  timezone: "Asia/Kolkata",
  status: "active",
  createdAt,
  updatedAt: createdAt,
};

export const DEMO_DEPARTMENTS: Department[] = [
  {
    id: DEMO_DEPARTMENT_IDS.operations,
    organizationId: DEMO_ORGANIZATION_ID,
    departmentCode: "OPS",
    departmentName: "Operations",
    description: "Project execution, DPR, field work and site teams.",
    hodUserId: "00000000-0000-4000-8000-000000000008",
    hodUserName: "Ananya Operations",
    userCount: 5,
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: DEMO_DEPARTMENT_IDS.civil,
    organizationId: DEMO_ORGANIZATION_ID,
    parentDepartmentId: DEMO_DEPARTMENT_IDS.operations,
    departmentCode: "CIV",
    departmentName: "Civil",
    description: "Civil works under Operations.",
    hodUserId: "00000000-0000-4000-8000-000000000008",
    hodUserName: "Ananya Operations",
    userCount: 3,
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: DEMO_DEPARTMENT_IDS.finance,
    organizationId: DEMO_ORGANIZATION_ID,
    departmentCode: "FIN",
    departmentName: "Finance",
    description: "Finance head, vouchers, ledgers and approvals.",
    hodUserId: "00000000-0000-4000-8000-000000000009",
    hodUserName: "Vikram Finance",
    userCount: 2,
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: DEMO_DEPARTMENT_IDS.accounts,
    organizationId: DEMO_ORGANIZATION_ID,
    parentDepartmentId: DEMO_DEPARTMENT_IDS.finance,
    departmentCode: "ACC",
    departmentName: "Accounts",
    description: "Payment processing, vouchers and ledgers.",
    hodUserId: "00000000-0000-4000-8000-000000000009",
    hodUserName: "Vikram Finance",
    userCount: 1,
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: DEMO_DEPARTMENT_IDS.hr,
    organizationId: DEMO_ORGANIZATION_ID,
    departmentCode: "HR",
    departmentName: "HR & Administration",
    description: "Users, HR records, attendance corrections and master data.",
    userCount: 1,
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
];

export const DEMO_DESIGNATIONS: Designation[] = [
  {
    id: DEMO_DESIGNATION_IDS.superAdmin,
    organizationId: DEMO_ORGANIZATION_ID,
    departmentId: DEMO_DEPARTMENT_IDS.finance,
    designationCode: "FIN-HEAD",
    designationName: "Finance Head / System Owner",
    levelRank: 100,
    description: "System owner with emergency override rights.",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: DEMO_DESIGNATION_IDS.departmentHod,
    organizationId: DEMO_ORGANIZATION_ID,
    designationCode: "HOD",
    designationName: "Department HOD",
    levelRank: 80,
    description: "Department-level workflow approver.",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: DEMO_DESIGNATION_IDS.projectManager,
    organizationId: DEMO_ORGANIZATION_ID,
    departmentId: DEMO_DEPARTMENT_IDS.operations,
    designationCode: "PM",
    designationName: "Project Manager",
    levelRank: 60,
    description: "Direct reporting manager for site teams.",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: DEMO_DESIGNATION_IDS.siteEngineer,
    organizationId: DEMO_ORGANIZATION_ID,
    departmentId: DEMO_DEPARTMENT_IDS.operations,
    designationCode: "SE",
    designationName: "Site Engineer",
    levelRank: 30,
    description: "Site user submitting attendance, claims, DPR and requests.",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: DEMO_DESIGNATION_IDS.adminExecutive,
    organizationId: DEMO_ORGANIZATION_ID,
    departmentId: DEMO_DEPARTMENT_IDS.hr,
    designationCode: "ADM-EXE",
    designationName: "Admin Executive",
    levelRank: 50,
    description: "Admin and HR verification role.",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: DEMO_DESIGNATION_IDS.accountsOfficer,
    organizationId: DEMO_ORGANIZATION_ID,
    departmentId: DEMO_DEPARTMENT_IDS.accounts,
    designationCode: "ACC-OFF",
    designationName: "Accounts Officer",
    levelRank: 50,
    description: "Payment and ledger processing role.",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
];

export const DEMO_APPROVAL_RULES: ApprovalMatrixRule[] = [
  {
    id: "00000000-0000-4000-8000-000000000501",
    organizationId: DEMO_ORGANIZATION_ID,
    workflowType: "claim",
    departmentId: DEMO_DEPARTMENT_IDS.operations,
    minAmount: 0,
    maxAmount: 5000,
    levels: [
      { role: "admin" },
      { role: "manager" },
      { role: "hod" },
      { role: "accounts" },
    ],
    finalApprovalRole: "hod",
    isActive: true,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "00000000-0000-4000-8000-000000000502",
    organizationId: DEMO_ORGANIZATION_ID,
    workflowType: "claim",
    departmentId: DEMO_DEPARTMENT_IDS.operations,
    minAmount: 5000,
    maxAmount: 50000,
    levels: [
      { role: "admin" },
      { role: "manager" },
      { role: "hod" },
      { role: "accounts" },
    ],
    finalApprovalRole: "hod",
    isActive: true,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "00000000-0000-4000-8000-000000000503",
    organizationId: DEMO_ORGANIZATION_ID,
    workflowType: "claim",
    minAmount: 50000,
    levels: [
      { role: "admin" },
      { role: "manager" },
      { role: "hod" },
      { role: "super_admin" },
      { role: "accounts" },
    ],
    finalApprovalRole: "super_admin",
    isActive: true,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "00000000-0000-4000-8000-000000000504",
    organizationId: DEMO_ORGANIZATION_ID,
    workflowType: "leave",
    departmentId: DEMO_DEPARTMENT_IDS.operations,
    levels: [{ role: "manager" }, { role: "hod" }],
    finalApprovalRole: "hod",
    isActive: true,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "00000000-0000-4000-8000-000000000505",
    organizationId: DEMO_ORGANIZATION_ID,
    workflowType: "material_request",
    departmentId: DEMO_DEPARTMENT_IDS.operations,
    levels: [{ role: "manager" }, { role: "hod" }, { role: "store_admin" }],
    finalApprovalRole: "store_admin",
    isActive: true,
    createdAt,
    updatedAt: createdAt,
  },
];

export const DEMO_DELEGATIONS: ApprovalDelegation[] = [];
