import { Download, FileSpreadsheet } from "lucide-react";
import autoTable from "jspdf-autotable";

import { Button } from "@/components/ui/Button";
import { ATTENDANCE_STATUS_LABELS } from "@/constants/attendance";
import { summarizeAttendance } from "@/hooks/useAttendanceSummary";
import type { AttendanceRecord, AttendanceStatus } from "@/types/attendance";

export interface ExportFilters { month: string; search: string; status: AttendanceStatus | "all"; projectName: string }
export function AttendanceExportActions({ records, filters }: { records: AttendanceRecord[]; filters: ExportFilters }) { return <div className="flex gap-2"><Button type="button" variant="secondary" aria-label="Export attendance as PDF" leftIcon={<Download className="h-4 w-4" />} onClick={() => void exportPdf(records, filters)}>PDF</Button><Button type="button" variant="secondary" aria-label="Export attendance as CSV" leftIcon={<FileSpreadsheet className="h-4 w-4" />} onClick={() => exportCsv(records, filters)}>CSV</Button></div>; }
function filterText(filters: ExportFilters) { return `Month: ${filters.month}; Status: ${filters.status === "all" ? "All" : ATTENDANCE_STATUS_LABELS[filters.status]}; Project: ${filters.projectName}; Search: ${filters.search || "None"}`; }
async function exportPdf(records: AttendanceRecord[], filters: ExportFilters) { const { jsPDF } = await import("jspdf"); const doc = new jsPDF({ orientation: "landscape" }); const summary = summarizeAttendance(records); doc.setFontSize(18); doc.text("Site Connect Attendance Register", 14, 16); doc.setFontSize(9); doc.text(`Generated: ${new Date().toLocaleString("en-IN")}`, 14, 23); doc.text(`Applied filters: ${filterText(filters)}`, 14, 29); doc.text(`Records: ${summary.total} | Present: ${summary.present} | Absent: ${summary.absent} | Attendance rate: ${summary.attendanceRate.toFixed(1)}% | Average hours: ${summary.averageHours.toFixed(1)}`, 14, 35); autoTable(doc, { startY: 40, head: [["Date", "Employee", "ID", "Project", "Status", "Check In", "Check Out", "Hours", "Remarks"]], body: records.map((record) => [record.date, record.userName, record.employeeId, record.projectName, ATTENDANCE_STATUS_LABELS[record.status], record.checkInTime ?? "-", record.checkOutTime ?? "-", record.workedHours.toFixed(1), record.remarks ?? ""]), styles: { fontSize: 7 }, headStyles: { fillColor: [0, 94, 184] } }); doc.save("attendance-register.pdf"); }
function exportCsv(records: AttendanceRecord[], filters: ExportFilters) { const escape = (value: unknown) => `"${String(value ?? "").split('"').join('""')}"`; const rows: unknown[][] = [["Generated Date", new Date().toLocaleString("en-IN")], ["Applied Filters", filterText(filters)], [], ["Date", "Employee", "Employee ID", "Project", "Status", "Check In", "Check Out", "Hours", "Remarks"], ...records.map((record) => [record.date, record.userName, record.employeeId, record.projectName, ATTENDANCE_STATUS_LABELS[record.status], record.checkInTime, record.checkOutTime, record.workedHours.toFixed(1), record.remarks])]; const blob = new Blob([`\uFEFF${rows.map((row) => row.map(escape).join(",")).join("\r\n")}`], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "attendance-register.csv"; link.click(); URL.revokeObjectURL(url); }
