-- One-time cleanup requested for the shared environment.
-- Keep authentication-linked profiles and organization/project configuration so
-- existing users can still sign in and create fresh operational records.
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'app_sessions',
    'audit_logs',
    'notifications',
    'notification_deliveries',
    'claim_approvals',
    'claim_attachments',
    'claim_items',
    'claims',
    'employee_ledgers',
    'payment_vouchers',
    'payments',
    'transactions',
    'attendance',
    'leave_approval_history',
    'leave_attachments',
    'leave_applications',
    'task_activity',
    'task_attachments',
    'task_comments',
    'tasks',
    'message_attachments',
    'message_reactions',
    'message_read_receipts',
    'messages',
    'conversation_members',
    'conversations',
    'dpr_activities',
    'dpr_issues',
    'dpr_photos',
    'daily_progress_reports',
    'casual_labour_bills',
    'casual_labour_attendance_rows',
    'casual_labour_attendance',
    'casual_labour_work_allocations',
    'labour_payees',
    'labour_contract_terms',
    'labour_rosters',
    'casual_labour_workers',
    'casual_labour_vendors',
    'machine_log_sessions',
    'machine_logs',
    'machine_breakdowns',
    'machinery_contract_machines',
    'machinery_contract_terms',
    'machine_assets',
    'machinery_contracts',
    'machinery_vendors',
    'fuel_issue_rows',
    'fuel_issues',
    'fuel_receipts',
    'fuel_stock_ledger',
    'fuel_vendor_ledger',
    'fuel_vendor_deposits',
    'fuel_contracts',
    'fuel_vendors',
    'material_receipt_attachments',
    'material_receipt_items',
    'material_receipts',
    'material_request_attachments',
    'material_request_items',
    'material_requests',
    'material_consumption',
    'material_stock_ledger',
    'materials',
    'material_vendors',
    'vendor_bill_items',
    'vendor_payments',
    'vendor_payment_vouchers',
    'vendor_ledgers',
    'vendor_ledger_entries',
    'vendor_bills',
    'vendor_contract_rate_cards',
    'vendor_contracts',
    'vendors',
    'report_exports',
    'user_invitations',
    'approval_delegations',
    'approval_matrices',
    'hierarchy_change_logs',
    'business_documents',
    'offline_mutations'
  ]
  loop
    if to_regclass('public.' || table_name) is not null then
      execute format('truncate table public.%I restart identity cascade', table_name);
    end if;
  end loop;
end
$$;
