alter table public.audit_logs add column if not exists actor_role text,add column if not exists remarks text,add column if not exists amount_before numeric(12,2),add column if not exists amount_after numeric(12,2),add column if not exists source text not null default 'web' check(source in('web','email_link','edge_function'));

create or replace view public.claim_ageing_report with(security_invoker=true) as
select c.organization_id,c.id claim_id,c.claim_number,p.full_name employee,pr.name project,c.submitted_at,c.status,
case when c.status='admin_verification_pending' then 'Admin' when c.status='manager_approval_pending' then 'Manager' when c.status in('hod_approval_pending','final_approval_pending') then 'HOD / Final Approver' when c.status in('accounts_verification_pending','accounts_returned') then 'Accounts' when c.status in('voucher_pending','sap_export_pending','payment_pending','partially_paid') then 'Accounts Payment' else '-' end pending_with,
greatest(0,current_date-coalesce(c.submitted_at::date,c.created_at::date)) ageing_days,c.total_approved amount
from public.claims c join public.user_profiles p on p.id=c.user_id left join public.projects pr on pr.id=c.project_id where c.deleted_at is null;
create or replace view public.claim_approval_delay_report with(security_invoker=true) as
select c.organization_id,c.id claim_id,c.claim_number,p.full_name employee,
coalesce(extract(epoch from(min(a.created_at)filter(where a.stage='admin_verification')-c.submitted_at))/3600,0) admin_hours,
coalesce(extract(epoch from(min(a.created_at)filter(where a.stage='manager_approval')-min(a.created_at)filter(where a.stage='admin_verification')))/3600,0) manager_hours,
coalesce(extract(epoch from(min(a.created_at)filter(where a.actor_role='hod')-min(a.created_at)filter(where a.stage='manager_approval')))/3600,0) hod_hours,
coalesce(extract(epoch from(min(a.created_at)filter(where a.actor_role='super_admin')-min(a.created_at)filter(where a.actor_role='hod')))/3600,0) super_admin_hours,
coalesce(extract(epoch from (min(av.verification_date)-max(a.created_at)filter(where a.stage='final_approval')))/3600,0) accounts_hours
from public.claims c join public.user_profiles p on p.id=c.user_id left join public.claim_approvals a on a.claim_id=c.id left join public.claim_accounts_verifications av on av.claim_id=c.id group by c.organization_id,c.id,c.claim_number,p.full_name,c.submitted_at;
create or replace view public.claim_project_cost_report with(security_invoker=true) as
select v.organization_id,coalesce(i.project_name_snapshot,'Unassigned') project,coalesce(i.customer_name_snapshot,'Unassigned') customer,coalesce(i.project_cost_code_snapshot,'Unassigned') cost_code,coalesce(i.expense_category_snapshot,'Unassigned') expense_category,sum(i.with_bill_amount) with_bill,sum(i.without_bill_amount) without_bill,sum(i.final_approved_amount) approved_amount,sum(i.deduction_amount) deduction,sum(coalesce(pay.paid,0)*case when v.net_payable_amount=0 then 0 else (i.final_approved_amount-i.deduction_amount)/v.net_payable_amount end) paid_amount
from public.claim_payment_vouchers v join public.claim_payment_voucher_items i on i.voucher_id=v.id left join(select voucher_id,sum(payment_amount) paid from public.claim_payments group by voucher_id)pay on pay.voucher_id=v.id group by v.organization_id,i.project_name_snapshot,i.customer_name_snapshot,i.project_cost_code_snapshot,i.expense_category_snapshot;
create or replace view public.claim_employee_ledger_report with(security_invoker=true) as
select l.organization_id,l.employee_id,p.full_name employee,sum(l.credit_amount)filter(where l.entry_type='opening_balance') opening,sum(l.credit_amount)filter(where l.entry_type='advance_added') advance,sum(l.debit_amount)filter(where l.entry_type='claim_submitted') submitted,sum(l.debit_amount)filter(where l.entry_type='claim_verified') approved,sum(l.credit_amount)filter(where l.entry_type='claim_deduction') deducted,sum(l.credit_amount)filter(where l.entry_type in('payment_processed','partial_payment')) paid,(array_agg(l.balance_after order by l.entry_date desc,l.created_at desc))[1] balance from public.employee_ledger_entries l join public.user_profiles p on p.id=l.employee_id group by l.organization_id,l.employee_id,p.full_name;
create or replace view public.claim_deduction_report with(security_invoker=true) as select c.organization_id,c.claim_number,p.full_name employee,c.total_claimed original_amount,c.total_approved approved_amount,greatest(c.total_claimed-c.total_approved,0) deduction,coalesce(av.accounts_remarks,a.remarks,'') deduction_reason,coalesce(vp.full_name,ap.full_name,'-') deducted_by from public.claims c join public.user_profiles p on p.id=c.user_id left join public.claim_accounts_verifications av on av.claim_id=c.id left join public.user_profiles vp on vp.id=av.verified_by left join lateral(select * from public.claim_approvals x where x.claim_id=c.id and x.amount_after<x.amount_before order by x.created_at desc limit 1)a on true left join public.user_profiles ap on ap.id=a.actor_id where greatest(c.total_claimed-c.total_approved,0)>0;
create or replace view public.claim_payment_pending_report with(security_invoker=true) as select v.organization_id,v.id voucher_id,v.voucher_number,v.employee_name_snapshot employee,v.net_payable_amount,case when bool_or(av.requires_sap_export) then max(av.sap_export_status) else 'not_required' end sap_status,v.payment_status,greatest(0,current_date-v.voucher_date) ageing_days from public.claim_payment_vouchers v join public.claim_payment_voucher_items i on i.voucher_id=v.id join public.claim_accounts_verifications av on av.claim_id=i.claim_id where v.payment_status in('pending','partially_paid') group by v.organization_id,v.id;
create or replace view public.claim_sap_export_report with(security_invoker=true) as select b.organization_id,b.sap_batch_number batch,b.export_date,v.voucher_number,c.claim_number,i.amount,i.sap_gl_code,i.sap_cost_center,p.full_name exported_by,b.status from public.claim_sap_export_batches b join public.claim_sap_export_items i on i.sap_batch_id=b.id join public.claim_payment_vouchers v on v.id=i.voucher_id join public.claims c on c.id=i.claim_id join public.user_profiles p on p.id=b.exported_by;
grant select on public.claim_ageing_report,public.claim_approval_delay_report,public.claim_project_cost_report,public.claim_employee_ledger_report,public.claim_deduction_report,public.claim_payment_pending_report,public.claim_sap_export_report to authenticated;
drop policy if exists "audit logs visible to admin roles" on public.audit_logs;
create policy "audit logs visible to authorized entity viewers" on public.audit_logs for select to authenticated using(public.current_user_role() in('admin_hr','accounts_officer','super_admin') or (entity_type='claim' and exists(select 1 from public.claims c where c.id=audit_logs.entity_id and (c.user_id=auth.uid() or c.reporting_manager_id=auth.uid() or c.hod_user_id=auth.uid()))));
